### PR TITLE
added my app Notekeeper

### PR DESCRIPTION
**Pull request by razorcalhn**
Hello, I am a fellow android developer from Delhi. I just want to showcase the app that I made some time ago. Feel free to give any feedback.
cheers 👍

### CODE REVIEW

**Comment by anirudh-jwala** [comment]
Missing code files, also omit files that are showcasing your file paths of your windows system

**Comment by razorcalhn** [comment]
okay, I've added the files and deleted the unnecessary ones, please let me know if there are more files which should be deleted.

**Comment by anirudh-jwala** [comment]
Notekeeper app will be a duplicate of the existing todo app in the repo, if you have anything else you can share it

**Comment by razorcalhn** [comment]
closing this PR, will send one for another app soon.

**Comment by razorcalhn** [comment]
Hi Anirudh, I've closed the PR for notekeeper and sent one for another app.
Let me know if this one works for you.

**Pull request closed without merging**
